# Generated by Django 5.0.3 on 2024-04-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('trainID', models.AutoField(primary_key=True, serialize=False)),
                ('to', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
    ]
